# Generated by Django 4.0 on 2022-09-23 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_timee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='timee_name',
        ),
    ]
